/* FragBot RA rocket-jump REPRODUCTION seam (generated by gen_rj_target.py). Mode 33.
 *
 * Reproduces the 14 human rocket-jumps-to-Red-Armor recorded on aerowalk. Each
 * recorded jump is a long RJ launched with a bunny-hop run-up (442-772 h-speed)
 * a standing bot cannot generate, so we reproduce it with REAL PHYSICS: teleport
 * to the jump's launch spot, inject the jump's launch velocity, play the rocket
 * sound, and let normal player physics fly the exact arc to RA (-320,480,448).
 * One setorigin + one velocity per jump (NOT a per-frame puppet); the flight is
 * real. Cycles all jumps forever. Telemetry (k_fb_rj_debug) reports per-jump min
 * distance to RA so we can verify each lands on the armor.
 *
 * NOTE: this REPRODUCES your recorded jumps (the genuine autonomous skill -- bot
 * bunny-hops for speed then RJs on its own -- is the harder next step). */
// FRAGBOT_ANCHOR: trap_makevectors(self->fb.desired_angle);
// FRAGBOT_FILE2: g_main.c
// FRAGBOT_ANCHOR2: sv_extensions = cvar("sv_mod_extensions");

/* ===== FRAGBOT_CALL2 ===== */
	cvar_set("qwm_ezcsqc", "0"); /* FragBot lab: standard rendering so bots are visible */
	localcmd("serverinfo fragbot_build \"@@FRAGBOT_BUILD@@\"\n"); /* deploy stamps this */
/* ===== /FRAGBOT_CALL2 ===== */

/* ===== FRAGBOT_BLOCK ===== */
#define FRAGBOT_RJ_MODE 33
#ifndef IT_ROCKET_LAUNCHER
#define IT_ROCKET_LAUNCHER 32
#endif

#define RA_X (-320.0f)
#define RA_Y ( 480.0f)
#define RA_Z ( 448.0f)
#define FRAGBOT_RJ_N 14
#define FRAGBOT_RJ_STUCK 220     /* ~2.8s airborne -> abort this jump, next */
#define FRAGBOT_RJ_PAUSE 90      /* ~1.2s on the ground between jumps */

/* {launch x,y,z, launch vx,vy,vz} per recorded jump */
static const float fragbot_rj_launch[FRAGBOT_RJ_N][6] = {
	{163.6f,464.5f,443.4f, -433.0f,89.0f,259.0f}  /* low_dmg_1  humanMinDistRA=15 */,
	{163.8f,445.8f,443.4f, -460.0f,-40.0f,259.0f}  /* low_dmg_2  humanMinDistRA=13 */,
	{177.8f,425.3f,443.4f, -396.0f,204.0f,259.0f}  /* low_dmg_3  humanMinDistRA=40 */,
	{182.9f,478.9f,443.4f, -327.0f,-3.0f,259.0f}  /* low_dmg_4  humanMinDistRA=51 */,
	{180.9f,420.0f,443.4f, -397.0f,132.0f,259.0f}  /* low_dmg_5  humanMinDistRA=10 */,
	{111.5f,536.0f,443.4f, -620.0f,-97.0f,440.0f}  /* full_dmg_1  humanMinDistRA=32 */,
	{126.8f,499.8f,452.3f, -647.0f,244.0f,433.0f}  /* full_dmg_2  humanMinDistRA=38 */,
	{111.8f,433.2f,460.6f, -609.0f,127.0f,386.0f}  /* full_dmg_3  humanMinDistRA=8 */,
	{109.6f,468.3f,451.7f, -543.0f,318.0f,390.0f}  /* full_dmg_4  humanMinDistRA=37 */,
	{174.8f,466.1f,451.6f, -521.0f,148.0f,378.0f}  /* full_dmg_5  humanMinDistRA=16 */,
	{368.0f,-57.3f,443.4f, -243.0f,733.0f,294.0f}  /* from_distance_1  humanMinDistRA=7 */,
	{368.0f,-73.6f,443.4f, -304.0f,693.0f,272.0f}  /* from_distance_2  humanMinDistRA=29 */,
	{78.1f,444.4f,483.8f, -452.0f,344.0f,364.0f}  /* from_distance_3  humanMinDistRA=9 */,
	{79.7f,430.2f,486.3f, -451.0f,443.0f,294.0f}  /* from_distance_4  humanMinDistRA=35 */
};

static int   fragbot_rj_idx[MAX_CLIENTS];     /* which recorded jump */
static int   fragbot_rj_phase[MAX_CLIENTS];   /* 0 place, 1 launch, 2 air, 3 pause */
static int   fragbot_rj_timer[MAX_CLIENTS];
static float fragbot_rj_mindist[MAX_CLIENTS]; /* closest approach to RA this jump */
static int   fragbot_rj_init[MAX_CLIENTS];
static int   fragbot_rj_dbgtick[MAX_CLIENTS];

static void FragBot_RJ(gedict_t *self)
{
	int slot = NUM_FOR_EDICT(self) - 1;
	int idx, onground;
	float dx, dy, dz, d;

	if (slot < 0 || slot >= MAX_CLIENTS) return;
	if (!fragbot_rj_init[slot]) {
		fragbot_rj_idx[slot] = 0;
		fragbot_rj_phase[slot] = 0;
		fragbot_rj_timer[slot] = 0;
		fragbot_rj_mindist[slot] = 99999.0f;
		fragbot_rj_init[slot] = 1;
	}
	idx = fragbot_rj_idx[slot];
	if (idx < 0 || idx >= FRAGBOT_RJ_N) idx = 0;
	onground = (int) self->s.v.flags & FL_ONGROUND;

	/* keep alive + armed (rocket is cosmetic here; velocity is injected) */
	self->s.v.items = ((int) self->s.v.items) | IT_ROCKET_LAUNCHER;
	if (self->s.v.ammo_rockets < 5) self->s.v.ammo_rockets = 50;
	if (self->s.v.health < 150) self->s.v.health = 250;
	self->s.v.weapon = IT_ROCKET_LAUNCHER;
	self->s.v.currentammo = self->s.v.ammo_rockets;
	self->fb.firing = false;
	self->fb.jumping = false;
	VectorClear(self->fb.dir_move_);

	/* aim toward RA (look where it is going) + track closest approach */
	dx = RA_X - self->s.v.origin[0];
	dy = RA_Y - self->s.v.origin[1];
	dz = RA_Z - self->s.v.origin[2];
	d = sqrt(dx*dx + dy*dy + dz*dz);
	if (d < fragbot_rj_mindist[slot]) fragbot_rj_mindist[slot] = d;

	if ((int) cvar("k_fb_rj_debug")) {
		if (++fragbot_rj_dbgtick[slot] >= 19) {
			fragbot_rj_dbgtick[slot] = 0;
			G_bprint(PRINT_HIGH, "RJ s%d jump%d ph%d og%d xyz %d %d %d distRA %d min %d\n",
				slot, idx, fragbot_rj_phase[slot], onground,
				(int) self->s.v.origin[0], (int) self->s.v.origin[1], (int) self->s.v.origin[2],
				(int) d, (int) fragbot_rj_mindist[slot]);
		}
	}

	switch (fragbot_rj_phase[slot]) {
	case 0: { /* PLACE: teleport to this jump's launch spot, settle 1 tick */
		vec3_t p;
		p[0] = fragbot_rj_launch[idx][0];
		p[1] = fragbot_rj_launch[idx][1];
		p[2] = fragbot_rj_launch[idx][2] + 4.0f;
		setorigin(self, PASSVEC3(p));
		VectorClear(self->s.v.velocity);
		fragbot_rj_mindist[slot] = 99999.0f;
		fragbot_rj_phase[slot] = 1;
		fragbot_rj_timer[slot] = 0;
		break;
	}
	case 1: /* LAUNCH: inject the recorded launch velocity + rocket sound -> arc */
		self->s.v.velocity[0] = fragbot_rj_launch[idx][3];
		self->s.v.velocity[1] = fragbot_rj_launch[idx][4];
		self->s.v.velocity[2] = fragbot_rj_launch[idx][5];
		sound(self, CHAN_WEAPON, "weapons/rocket1i.wav", 1, ATTN_NORM);
		fragbot_rj_phase[slot] = 2;
		fragbot_rj_timer[slot] = 0;
		break;

	case 2: /* AIR: air-strafe toward RA (like the human did) + real physics */
		{
			float ax = RA_X - self->s.v.origin[0];
			float ay = RA_Y - self->s.v.origin[1];
			float al = sqrt(ax * ax + ay * ay);
			if (al > 1.0f) {
				self->fb.dir_move_[0] = ax / al;   /* steer the move toward RA */
				self->fb.dir_move_[1] = ay / al;
				self->fb.dir_move_[2] = 0;
				self->fb.desired_angle[YAW] = atan2(ay, ax) * 180.0f / 3.14159265f;
			}
		}
		fragbot_rj_timer[slot] += 1;
		if ((fragbot_rj_timer[slot] > 8 && onground) || fragbot_rj_timer[slot] > FRAGBOT_RJ_STUCK) {
			if ((int) cvar("k_fb_rj_debug"))
				G_bprint(2, "RJ s%d jump%d RESULT minDistRA=%d %s\n", slot, idx,
					(int) fragbot_rj_mindist[slot],
					fragbot_rj_mindist[slot] < 64.0f ? "REACHED" : "missed");
			fragbot_rj_phase[slot] = 3;
			fragbot_rj_timer[slot] = FRAGBOT_RJ_PAUSE;
		}
		break;

	case 3: /* PAUSE then advance to the next recorded jump */
		fragbot_rj_timer[slot] -= 1;
		if (fragbot_rj_timer[slot] <= 0) {
			fragbot_rj_idx[slot] = (idx + 1) % FRAGBOT_RJ_N;
			fragbot_rj_phase[slot] = 0;
			fragbot_rj_timer[slot] = 0;
		}
		break;
	}
}
/* ===== /FRAGBOT_BLOCK ===== */

/* ===== FRAGBOT_CALL ===== */
	/* RJ launch coords are aerowalk-specific; the deploy pins the server to aerowalk
	 * (port cfg + matchless cfg) so we don't need an in-code map guard (which was
	 * silently blocking this and dropping the bot to the stock frogbot). */
	if ((int) cvar("k_fb_fragbot_mode") == FRAGBOT_RJ_MODE && !ISDEAD(self))
	{
		FragBot_RJ(self);
	}
/* ===== /FRAGBOT_CALL ===== */
