#!/usr/bin/env python3
"""Generate the FragBot REPLAY seam (.c) from a komodo replay .cmds file.

Open-loop replay: embeds the human trace (start origin+velocity + per-frame view
angles / move command / jump) as a C array, plus our own clean replay mode hooked
into bot_movement.c. On frame 0 it teleports the bot to the human's start state,
then emits the recorded inputs each frame, looping at the end so it runs the trick
over and over. This is FragBot's own code — it only PLAYS BACK human inputs (no
movement-brain logic), so it doesn't depend on komodo's (phone-built) controllers.

.cmds columns: msec ox oy oz vx vy vz pitch yaw roll fwd side up buttons
Usage: gen_replay_seam.py <in.cmds> <out_seam.c> <MODE_INT>
"""
import sys

cmds_path, out_path, mode = sys.argv[1], sys.argv[2], int(sys.argv[3])
rows = []
o0 = v0 = None
for line in open(cmds_path):
    line = line.strip()
    if not line or line.startswith("#"):
        continue
    p = line.split()
    if len(p) < 14:
        continue
    msec = p[0]; ox, oy, oz = p[1:4]; vx, vy, vz = p[4:7]
    pitch, yaw, roll = p[7:10]; fwd, side, up = p[10:13]; buttons = p[13]
    if o0 is None:
        o0 = (ox, oy, oz); v0 = (vx, vy, vz)
    rows.append((pitch, yaw, fwd, side, up, buttons))

n = len(rows)
def fl(x):
    return repr(float(x)) + "f"   # always a valid C float literal (e.g. 9.0f)
arr = ",\n".join(
    "  {%s,%s,%s,%s,%s,%d}" % (fl(pitch), fl(yaw), fl(fwd), fl(side), fl(up), int(float(buttons)))
    for (pitch, yaw, fwd, side, up, buttons) in rows
)

seam = f"""/* FragBot REPLAY seam (generated by gen_replay_seam.py — do not hand-edit).
 * Open-loop replay of a human .qwd trace: teleport to the human start, then emit
 * the recorded view+move+jump each frame, looping. Plays back human input only. */

/* ===== FRAGBOT_BLOCK ===== */
#define FRAGBOT_REPLAY_MODE {mode}
#define FRAGBOT_REPLAY_FRAMES {n}
static const float fragbot_replay_origin[3] = {{ {fl(o0[0])}, {fl(o0[1])}, {fl(o0[2])} }};
static const float fragbot_replay_vel[3]    = {{ {fl(v0[0])}, {fl(v0[1])}, {fl(v0[2])} }};
/* per frame: pitch, yaw, forwardmove, sidemove, upmove, buttons */
static const float fragbot_replay[FRAGBOT_REPLAY_FRAMES][6] = {{
{arr}
}};
static int fragbot_rframe[MAX_CLIENTS];

static void FragBot_Replay(gedict_t *self, vec3_t direction, qbool *jumping, qbool *firing)
{{
	int slot = NUM_FOR_EDICT(self) - 1;
	int f;
	if (slot < 0 || slot >= MAX_CLIENTS) return;
	f = fragbot_rframe[slot];
	if (f < 0 || f >= FRAGBOT_REPLAY_FRAMES) f = 0;   /* loop the trick */
	if (f == 0) {{                                     /* snap to the human start */
		vec3_t o, v;
		o[0] = fragbot_replay_origin[0]; o[1] = fragbot_replay_origin[1]; o[2] = fragbot_replay_origin[2];
		v[0] = fragbot_replay_vel[0];    v[1] = fragbot_replay_vel[1];    v[2] = fragbot_replay_vel[2];
		setorigin(self, PASSVEC3(o));
		VectorCopy(v, self->s.v.velocity);
	}}
	self->fb.desired_angle[PITCH] = fragbot_replay[f][0];
	self->fb.desired_angle[YAW]   = fragbot_replay[f][1];
	self->fb.desired_angle[ROLL]  = 0;
	direction[0] = fragbot_replay[f][2];
	direction[1] = fragbot_replay[f][3];
	direction[2] = fragbot_replay[f][4];
	*jumping = (((int) fragbot_replay[f][5]) & 2) ? true : false;
	*firing  = false;
	fragbot_rframe[slot] = f + 1;
}}
/* ===== /FRAGBOT_BLOCK ===== */

/* ===== FRAGBOT_CALL ===== */
	if ((int) cvar("k_fb_fragbot_mode") == FRAGBOT_REPLAY_MODE && !ISDEAD(self)
	    && !(match_in_progress != 2 && cvar(FB_CVAR_FREEZE_PREWAR)))
	{{
		FragBot_Replay(self, direction, &jumping, &firing);
	}}
/* ===== /FRAGBOT_CALL ===== */
"""
open(out_path, "w").write(seam)
print(f"wrote {out_path}: {n} frames, start origin {o0}, vel {v0}")
