#!/usr/bin/env python3
"""Generate the FragBot RA-rocket-jump REPRODUCTION seam (mode 33) from the
human .qwd traces in rj_traces.json.

Each recorded jump is a real long rocket jump to aerowalk Red Armor (-320,480,448)
launched with a bunny-hop run-up (442-772 h-speed) that a standing bot cannot
generate. So we reproduce each jump FAITHFULLY with real physics: teleport the
bot to that jump's launch position, inject that jump's launch velocity, play the
rocket fire sound, then let normal player physics carry the exact arc to RA.
NOT a per-frame puppet (one setorigin + one velocity per jump); the flight is
real physics. Cycles all traces so every recorded RA jump can be watched + the
harness can verify closest-approach to RA per jump.

Emits fragbot_rj_seam.c with the ezcsqc-off 2nd injection (lab visibility) +
cvar-gated telemetry (k_fb_rj_debug) reporting per-jump min distance to RA.
"""
import json, math
from pathlib import Path

HERE = Path(__file__).resolve().parent
cfg = json.load(open(HERE / "rj_traces.json"))
traces = cfg["traces"]
RA = (-320.0, 480.0, 448.0)

rows, names = [], []
for t in traces:
    f = t["frames"]
    li = max(range(len(f)), key=lambda i: f[i][6])   # launch = peak upward vz
    lf = f[li]
    lx, ly, lz, vx, vy, vz = lf[1], lf[2], lf[3], lf[4], lf[5], lf[6]
    md = min(math.dist((fr[1], fr[2], fr[3]), RA) for fr in f)
    rows.append("\t{%.1ff,%.1ff,%.1ff, %.1ff,%.1ff,%.1ff}  /* %s  humanMinDistRA=%.0f */"
                % (lx, ly, lz, vx, vy, vz, t["name"], md))
    names.append(t["name"])
N = len(rows)
arr = ",\n".join(rows)

seam = '''/* FragBot RA rocket-jump REPRODUCTION seam (generated by gen_rj_target.py). Mode 33.
 *
 * Reproduces the %(n)d human rocket-jumps-to-Red-Armor recorded on aerowalk. Each
 * recorded jump is a long RJ launched with a bunny-hop run-up (442-772 h-speed)
 * a standing bot cannot generate, so we reproduce it with REAL PHYSICS: teleport
 * to the jump's launch spot, inject the jump's launch velocity, play the rocket
 * sound, and let normal player physics fly the exact arc to RA (-320,480,448).
 * One setorigin + one velocity per jump (NOT a per-frame puppet); the flight is
 * real. Cycles all jumps forever. Telemetry (k_fb_rj_debug) reports per-jump min
 * distance to RA so we can verify each lands on the armor.
 *
 * NOTE: this REPRODUCES your recorded jumps (the genuine autonomous skill -- bot
 * bunny-hops for speed then RJs on its own -- is the harder next step). */
// FRAGBOT_ANCHOR: trap_makevectors(self->fb.desired_angle);
// FRAGBOT_FILE2: g_main.c
// FRAGBOT_ANCHOR2: sv_extensions = cvar("sv_mod_extensions");

/* ===== FRAGBOT_CALL2 ===== */
\tcvar_set("qwm_ezcsqc", "0"); /* FragBot lab: standard rendering so bots are visible */
/* ===== /FRAGBOT_CALL2 ===== */

/* ===== FRAGBOT_BLOCK ===== */
#define FRAGBOT_RJ_MODE 33
#ifndef IT_ROCKET_LAUNCHER
#define IT_ROCKET_LAUNCHER 32
#endif

#define RA_X (-320.0f)
#define RA_Y ( 480.0f)
#define RA_Z ( 448.0f)
#define FRAGBOT_RJ_N %(n)d
#define FRAGBOT_RJ_STUCK 220     /* ~2.8s airborne -> abort this jump, next */
#define FRAGBOT_RJ_PAUSE 90      /* ~1.2s on the ground between jumps */

/* {launch x,y,z, launch vx,vy,vz} per recorded jump */
static const float fragbot_rj_launch[FRAGBOT_RJ_N][6] = {
%(arr)s
};

static int   fragbot_rj_idx[MAX_CLIENTS];     /* which recorded jump */
static int   fragbot_rj_phase[MAX_CLIENTS];   /* 0 place, 1 launch, 2 air, 3 pause */
static int   fragbot_rj_timer[MAX_CLIENTS];
static float fragbot_rj_mindist[MAX_CLIENTS]; /* closest approach to RA this jump */
static int   fragbot_rj_init[MAX_CLIENTS];
static int   fragbot_rj_dbgtick[MAX_CLIENTS];

static void FragBot_RJ(gedict_t *self)
{
\tint slot = NUM_FOR_EDICT(self) - 1;
\tint idx, onground;
\tfloat dx, dy, dz, d;

\tif (slot < 0 || slot >= MAX_CLIENTS) return;
\tif (!fragbot_rj_init[slot]) {
\t\tfragbot_rj_idx[slot] = 0;
\t\tfragbot_rj_phase[slot] = 0;
\t\tfragbot_rj_timer[slot] = 0;
\t\tfragbot_rj_mindist[slot] = 99999.0f;
\t\tfragbot_rj_init[slot] = 1;
\t}
\tidx = fragbot_rj_idx[slot];
\tif (idx < 0 || idx >= FRAGBOT_RJ_N) idx = 0;
\tonground = (int) self->s.v.flags & FL_ONGROUND;

\t/* keep alive + armed (rocket is cosmetic here; velocity is injected) */
\tself->s.v.items = ((int) self->s.v.items) | IT_ROCKET_LAUNCHER;
\tif (self->s.v.ammo_rockets < 5) self->s.v.ammo_rockets = 50;
\tif (self->s.v.health < 150) self->s.v.health = 250;
\tself->s.v.weapon = IT_ROCKET_LAUNCHER;
\tself->s.v.currentammo = self->s.v.ammo_rockets;
\tself->fb.firing = false;
\tself->fb.jumping = false;
\tVectorClear(self->fb.dir_move_);

\t/* aim toward RA (look where it is going) + track closest approach */
\tdx = RA_X - self->s.v.origin[0];
\tdy = RA_Y - self->s.v.origin[1];
\tdz = RA_Z - self->s.v.origin[2];
\td = sqrt(dx*dx + dy*dy + dz*dz);
\tif (d < fragbot_rj_mindist[slot]) fragbot_rj_mindist[slot] = d;

\tif ((int) cvar("k_fb_rj_debug")) {
\t\tif (++fragbot_rj_dbgtick[slot] >= 19) {
\t\t\tfragbot_rj_dbgtick[slot] = 0;
\t\t\tG_bprint(PRINT_HIGH, "RJ s%%d jump%%d ph%%d og%%d xyz %%d %%d %%d distRA %%d min %%d\\n",
\t\t\t\tslot, idx, fragbot_rj_phase[slot], onground,
\t\t\t\t(int) self->s.v.origin[0], (int) self->s.v.origin[1], (int) self->s.v.origin[2],
\t\t\t\t(int) d, (int) fragbot_rj_mindist[slot]);
\t\t}
\t}

\tswitch (fragbot_rj_phase[slot]) {
\tcase 0: { /* PLACE: teleport to this jump's launch spot, settle 1 tick */
\t\tvec3_t p;
\t\tp[0] = fragbot_rj_launch[idx][0];
\t\tp[1] = fragbot_rj_launch[idx][1];
\t\tp[2] = fragbot_rj_launch[idx][2] + 4.0f;
\t\tsetorigin(self, PASSVEC3(p));
\t\tVectorClear(self->s.v.velocity);
\t\tfragbot_rj_mindist[slot] = 99999.0f;
\t\tfragbot_rj_phase[slot] = 1;
\t\tfragbot_rj_timer[slot] = 0;
\t\tbreak;
\t}
\tcase 1: /* LAUNCH: inject the recorded launch velocity + rocket sound -> arc */
\t\tself->s.v.velocity[0] = fragbot_rj_launch[idx][3];
\t\tself->s.v.velocity[1] = fragbot_rj_launch[idx][4];
\t\tself->s.v.velocity[2] = fragbot_rj_launch[idx][5];
\t\tsound(self, CHAN_WEAPON, "weapons/rocket1i.wav", 1, ATTN_NORM);
\t\tfragbot_rj_phase[slot] = 2;
\t\tfragbot_rj_timer[slot] = 0;
\t\tbreak;

\tcase 2: /* AIR: air-strafe toward RA (like the human did) + real physics */
\t\t{
\t\t\tfloat ax = RA_X - self->s.v.origin[0];
\t\t\tfloat ay = RA_Y - self->s.v.origin[1];
\t\t\tfloat al = sqrt(ax * ax + ay * ay);
\t\t\tif (al > 1.0f) {
\t\t\t\tself->fb.dir_move_[0] = ax / al;   /* steer the move toward RA */
\t\t\t\tself->fb.dir_move_[1] = ay / al;
\t\t\t\tself->fb.dir_move_[2] = 0;
\t\t\t\tself->fb.desired_angle[YAW] = atan2(ay, ax) * 180.0f / 3.14159265f;
\t\t\t}
\t\t}
\t\tfragbot_rj_timer[slot] += 1;
\t\tif ((fragbot_rj_timer[slot] > 8 && onground) || fragbot_rj_timer[slot] > FRAGBOT_RJ_STUCK) {
\t\t\tif ((int) cvar("k_fb_rj_debug"))
\t\t\t\tG_bprint(2, "RJ s%%d jump%%d RESULT minDistRA=%%d %%s\\n", slot, idx,
\t\t\t\t\t(int) fragbot_rj_mindist[slot],
\t\t\t\t\tfragbot_rj_mindist[slot] < 64.0f ? "REACHED" : "missed");
\t\t\tfragbot_rj_phase[slot] = 3;
\t\t\tfragbot_rj_timer[slot] = FRAGBOT_RJ_PAUSE;
\t\t}
\t\tbreak;

\tcase 3: /* PAUSE then advance to the next recorded jump */
\t\tfragbot_rj_timer[slot] -= 1;
\t\tif (fragbot_rj_timer[slot] <= 0) {
\t\t\tfragbot_rj_idx[slot] = (idx + 1) %% FRAGBOT_RJ_N;
\t\t\tfragbot_rj_phase[slot] = 0;
\t\t\tfragbot_rj_timer[slot] = 0;
\t\t}
\t\tbreak;
\t}
}
/* ===== /FRAGBOT_BLOCK ===== */

/* ===== FRAGBOT_CALL ===== */
\t/* aerowalk-ONLY: the RA launch coords are aerowalk-specific. On any other map
\t * (e.g. a matchless rotation to dm6) teleporting there lands in the void and
\t * the bot dies -> reverts to a native nailgun frogbot. Guard hard on the map. */
\tif ((int) cvar("k_fb_fragbot_mode") == FRAGBOT_RJ_MODE && !ISDEAD(self)
\t    && streq(mapname, "aerowalk"))
\t{
\t\tFragBot_RJ(self);
\t}
/* ===== /FRAGBOT_CALL ===== */
''' % {"n": N, "arr": arr, "names0": names[0]}

out = HERE / "fragbot_rj_seam.c"
out.write_text(seam)
print("wrote %s (%d jumps)" % (out, N))
