#!/usr/bin/env python3
"""FragBot RJ-REPLAY seam generator (mode 33) — rocket-jump demonstrator.

Reads rj_traces.json (exported by ../qwd_rj.py --export) and emits a KTX C seam
that puppets ONE bot through every successful rocket-jump trace in sequence,
cycling + looping forever so it can be watched on aerowalk.

Each trace is a list of [msec, ox,oy,oz, vx,vy,vz, pitch, yaw] frames. Per frame
the bot is teleported to the human's exact origin + velocity + view, armed +
invuln. On the LAUNCH frame (peak upward vz) it plays a rocket-fire sound and
fires a visible rocket. At the end of a trace it advances to the next trace
(setorigin teleports to the new trace's first frame), pauses briefly, and loops.

Modeled exactly on gen_replay_seam.py / fragbot_replay_seam.c idioms:
  FRAGBOT_BLOCK injected before `void BotSetCommand`; FRAGBOT_CALL before
  `trap_makevectors(self->fb.desired_angle)` (declared via the FRAGBOT_ANCHOR
  line like the path seam); per-slot state arrays sized MAX_CLIENTS; each frame
  setorigin(self, PASSVEC3(o)) + VectorCopy(vel, self->s.v.velocity); sets
  self->fb.desired_angle[PITCH/YAW] + self->s.v.angles for the model.

Usage: gen_rj_seam.py [traces.json] [out_seam.c]
Stdlib only.
"""
import sys
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
traces_path = Path(sys.argv[1]) if len(sys.argv) > 1 else HERE / "rj_traces.json"
out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else HERE / "fragbot_rj_seam.c"

MODE = 33


def fl(x):
    return repr(float(x)) + "f"


cfg = json.load(open(traces_path))
traces = cfg["traces"]
if not traces:
    sys.exit("no traces in %s" % traces_path)


def launch_frame(frames):
    """Index of the launch frame = the frame of peak upward vz (index 6)."""
    best_i, best_vz = 0, frames[0][6]
    for i, fr in enumerate(frames):
        if fr[6] > best_vz:
            best_vz, best_i = fr[6], i
    return best_i


arrays, dispatch_n, dispatch_arr, summary = [], [], [], []
for idx, t in enumerate(traces):
    frames = t["frames"]
    n = len(frames)
    lf = launch_frame(frames)
    # column 9 (after msec,o,v,pitch,yaw at 0..8) flags the launch frame so the
    # seam fires a rocket + plays the launch sound exactly at takeoff.
    rows = []
    for fi, fr in enumerate(frames):
        msec = int(fr[0])
        vals = ",".join(fl(v) for v in fr[1:9])   # ox..yaw (8 floats)
        fire = 1 if fi == lf else 0
        rows.append("  {%d,%s,%d}" % (msec, vals, fire))
    body = ",\n".join(rows)
    arrays.append(
        "#define FRAGBOT_RJ_N_%d %d\n"
        "static const float fragbot_rj_%d[FRAGBOT_RJ_N_%d][10] = {\n%s\n};"
        % (idx, n, idx, idx, body)
    )
    dispatch_n.append("\tif (which == %d) return FRAGBOT_RJ_N_%d;" % (idx, idx))
    dispatch_arr.append("\tif (which == %d) return fragbot_rj_%d;" % (idx, idx))
    summary.append("%s(%d,launch@%d)" % (t["name"], n, lf))

NUM = len(traces)

seam = """/* FragBot RJ-REPLAY seam (generated by gen_rj_seam.py). Mode %(mode)d.
 * Rocket-jump demonstrator: puppets ONE bot through every SUCCESSFUL rocket-jump
 * trace exported from human .qwd demos, cycling through all %(num)d traces and
 * looping forever so the full set can be watched on aerowalk.
 *
 * Per frame: teleport to the human's exact origin+velocity+view, armed+invuln.
 * On the LAUNCH frame (peak upward vz) play a rocket-fire sound + fire a rocket.
 * At trace end: advance trace index (mod %(num)d), reset frame to 0 (setorigin
 * teleports to the next trace's first frame), brief pause, loop.
 *
 * Traces: %(summary)s.
 * Each row: {msec, ox,oy,oz, vx,vy,vz, pitch, yaw, is_launch}. */
// FRAGBOT_ANCHOR: trap_makevectors(self->fb.desired_angle);

/* ===== FRAGBOT_BLOCK ===== */
#define FRAGBOT_RJ_MODE %(mode)d
#define FRAGBOT_RJ_NUM_TRACES %(num)d
#define FRAGBOT_RJ_PAUSE_FRAMES 30      /* ~0.4s pause between traces (~77Hz) */

%(arrays)s

static int FragBot_RJ_TraceLen(int which)
{
%(dispatch_n)s
	return 0;
}
static const float (*FragBot_RJ_Trace(int which))[10]
{
%(dispatch_arr)s
	return (const float (*)[10]) 0;
}

static int fragbot_rj_trace[MAX_CLIENTS];   /* current trace index */
static int fragbot_rj_frame[MAX_CLIENTS];   /* current frame within the trace */
static int fragbot_rj_pause[MAX_CLIENTS];   /* remaining pause frames between traces */
static int fragbot_rj_init[MAX_CLIENTS];

static void FragBot_RJ(gedict_t *self, vec3_t direction, qbool *jumping,
                       qbool *firing)
{
	int slot = NUM_FOR_EDICT(self) - 1;
	int which, count, f;
	const float (*tr)[10];
	vec3_t o, vel;

	if (slot < 0 || slot >= MAX_CLIENTS) return;

	if (!fragbot_rj_init[slot]) {
		fragbot_rj_trace[slot] = 0;
		fragbot_rj_frame[slot] = 0;
		fragbot_rj_pause[slot] = 0;
		fragbot_rj_init[slot] = 1;
	}

	/* arm + invuln so the puppet survives the self-damage and shows a rocket */
	self->s.v.items = ((int) self->s.v.items) | 127;
	self->s.v.ammo_shells = 200; self->s.v.ammo_nails = 200;
	self->s.v.ammo_rockets = 100; self->s.v.ammo_cells = 200;
	self->s.v.health = 1000; self->s.v.takedamage = DAMAGE_NO;

	VectorClear(direction);
	*jumping = false;
	*firing = false;

	/* brief pause between traces — hold still on the last frame's spot */
	if (fragbot_rj_pause[slot] > 0) {
		fragbot_rj_pause[slot] -= 1;
		return;
	}

	which = fragbot_rj_trace[slot];
	if (which < 0 || which >= FRAGBOT_RJ_NUM_TRACES) which = 0;
	count = FragBot_RJ_TraceLen(which);
	tr = FragBot_RJ_Trace(which);
	if (!tr || count <= 0) return;

	f = fragbot_rj_frame[slot];
	if (f >= count) {
		/* finished a trace -> advance (cycler), reset frame, pause, loop */
		fragbot_rj_trace[slot] = (which + 1) %% FRAGBOT_RJ_NUM_TRACES;
		fragbot_rj_frame[slot] = 0;
		fragbot_rj_pause[slot] = FRAGBOT_RJ_PAUSE_FRAMES;
		return;
	}
	if (f < 0) f = 0;

	/* puppet origin + velocity */
	o[0]   = tr[f][1]; o[1]   = tr[f][2]; o[2]   = tr[f][3];
	vel[0] = tr[f][4]; vel[1] = tr[f][5]; vel[2] = tr[f][6];
	setorigin(self, PASSVEC3(o));
	VectorCopy(vel, self->s.v.velocity);

	/* view: drive both the aim and the 3rd-person model angles */
	self->fb.desired_angle[PITCH] = tr[f][7];
	self->fb.desired_angle[YAW]   = tr[f][8];
	self->fb.desired_angle[ROLL]  = 0;
	self->s.v.angles[0] = tr[f][7];
	self->s.v.angles[1] = tr[f][8];
	self->s.v.angles[2] = 0;

	/* LAUNCH frame: fire a visible rocket + play the launch sound */
	if (tr[f][9] != 0.0f) {
		sound(self, CHAN_WEAPON, "weapons/rocket1i.wav", 1, ATTN_NORM);
		*firing = true;
	}

	fragbot_rj_frame[slot] = f + 1;
}
/* ===== /FRAGBOT_BLOCK ===== */

/* ===== FRAGBOT_CALL ===== */
	if ((int) cvar("k_fb_fragbot_mode") == FRAGBOT_RJ_MODE && !ISDEAD(self))
	{
		FragBot_RJ(self, direction, &jumping, &firing);
	}
/* ===== /FRAGBOT_CALL ===== */
""" % {
    "mode": MODE,
    "num": NUM,
    "summary": " ".join(summary),
    "arrays": "\n".join(arrays),
    "dispatch_n": "\n".join(dispatch_n),
    "dispatch_arr": "\n".join(dispatch_arr),
}

out_path.write_text(seam)
print("wrote %s: %d traces | %s" % (out_path, NUM, " ".join(summary)))
