#!/usr/bin/env python3
"""Generate the FragBot WALK-then-REPLAY RA seam (mode 33) from rj_traces.json.

User's design: a bot must NEVER be placed mid-air. So instead of teleporting to a
mid-jump launch coordinate, the bot:
  1. spawns at a normal spawn point (on the ground),
  2. WALKS to the spot where a recording starts (frame 0, on the ground),
  3. then REPLAYS that recorded jump frame-by-frame (the human's exact run-up ->
     jump -> rocket -> flight to Red Armor), firing the rocket sound at launch,
  4. pauses, advances to the next recording, walks there, replays, forever.

The only airborne motion is the real recorded jump arc. Replay is a dense (~77Hz)
position playback so it reads as smooth movement, not teleporting. If the walk
can't reach the start within a timeout, it snaps to the (grounded) start as a
fallback -- still never mid-air.

Emits fragbot_rj_seam.c with the ezcsqc-off + build-stamp injections (lab
visibility + deploy verification). Stdlib only.
"""
import json, math
from pathlib import Path

HERE = Path(__file__).resolve().parent
cfg = json.load(open(HERE / "rj_traces.json"))
traces = cfg["traces"]
RA = (-320.0, 480.0, 448.0)

def launch_frame(frames):
    bi, bv = 0, frames[0][6]
    for i, fr in enumerate(frames):
        if fr[6] > bv:
            bv, bi = fr[6], i
    return bi

def fl(x):
    return repr(round(float(x), 1)) + "f"

arrays, lens, lfs, names = [], [], [], []
for idx, t in enumerate(traces):
    f = t["frames"]
    lf = launch_frame(f)
    rows = []
    for fi, fr in enumerate(f):
        # store x,y,z, vx,vy,vz, pitch, yaw, is_launch
        vals = ",".join(fl(v) for v in (fr[1], fr[2], fr[3], fr[4], fr[5], fr[6], fr[7], fr[8]))
        rows.append("  {%s,%d}" % (vals, 1 if fi == lf else 0))
    arrays.append("static const float fbw_%d[%d][9] = {\n%s\n};" % (idx, len(f), ",\n".join(rows)))
    lens.append(len(f)); lfs.append(lf); names.append(t["name"])

N = len(traces)
dispatch_arr = "\n".join("\tif (w == %d) return fbw_%d;" % (i, i) for i in range(N))
dispatch_len = "\n".join("\tif (w == %d) return %d;" % (i, lens[i]) for i in range(N))

seam = '''/* FragBot WALK-then-REPLAY RA seam (generated by gen_rj_walk.py). Mode 33.
 * Bot spawns on the ground, WALKS to a recording's start point, then REPLAYS the
 * recorded jump (run-up -> RJ -> Red Armor). Never placed mid-air. %(num)d jumps.
 * Each frame row: {x,y,z, vx,vy,vz, pitch, yaw, is_launch}. */
// FRAGBOT_ANCHOR: trap_makevectors(self->fb.desired_angle);
// FRAGBOT_FILE2: g_main.c
// FRAGBOT_ANCHOR2: sv_extensions = cvar("sv_mod_extensions");

/* ===== FRAGBOT_CALL2 ===== */
\tcvar_set("qwm_ezcsqc", "0");
\tlocalcmd("serverinfo fragbot_build \\"@@FRAGBOT_BUILD@@\\"\\n");
/* ===== /FRAGBOT_CALL2 ===== */

/* ===== FRAGBOT_BLOCK ===== */
#ifndef IT_ROCKET_LAUNCHER
#define IT_ROCKET_LAUNCHER 32
#endif
#define FBW_N %(num)d
#define FBW_WALK_TIMEOUT 500   /* ~6.5s to reach the start, else snap (grounded) */
#define FBW_PAUSE 60           /* ~0.8s between jumps */
#define FBW_ARRIVE 40.0f       /* within this horizontal dist = arrived */

%(arrays)s

static const float (*FBW_Trace(int w))[9]
{
%(disp_arr)s
\treturn (const float (*)[9]) 0;
}
static int FBW_Len(int w)
{
%(disp_len)s
\treturn 0;
}

static int   fbw_idx[MAX_CLIENTS];     /* which recorded jump */
static int   fbw_phase[MAX_CLIENTS];   /* 0 walk, 1 replay, 2 pause */
static int   fbw_fi[MAX_CLIENTS];      /* replay frame index */
static int   fbw_timer[MAX_CLIENTS];
static int   fbw_init[MAX_CLIENTS];

static void FragBot_RJ(gedict_t *self)
{
\tint slot = NUM_FOR_EDICT(self) - 1;
\tint idx, n, og;
\tconst float (*tr)[9];

\tif (slot < 0 || slot >= MAX_CLIENTS) return;
\tif (!fbw_init[slot]) { fbw_idx[slot]=0; fbw_phase[slot]=0; fbw_fi[slot]=0; fbw_timer[slot]=0; fbw_init[slot]=1; }
\tidx = fbw_idx[slot]; if (idx < 0 || idx >= FBW_N) idx = 0;
\ttr = FBW_Trace(idx); n = FBW_Len(idx);
\tif (!tr || n <= 0) return;
\tog = (int) self->s.v.flags & FL_ONGROUND;

\tif ((int) cvar("k_fb_rj_debug")) { static int dt[MAX_CLIENTS]; if (++dt[slot] >= 19) { dt[slot]=0;
\t\tG_bprint(2, "RJW s%%d ph%%d og%%d xyz %%d %%d %%d\\n", slot, fbw_phase[slot], og,
\t\t\t(int)self->s.v.origin[0], (int)self->s.v.origin[1], (int)self->s.v.origin[2]); } }

\t/* keep RL so the launch sound/visual is a rocket */
\tself->s.v.items = ((int) self->s.v.items) | IT_ROCKET_LAUNCHER;
\tif (self->s.v.ammo_rockets < 5) self->s.v.ammo_rockets = 50;
\tif (self->s.v.health < 100) self->s.v.health = 200;
\tself->s.v.weapon = IT_ROCKET_LAUNCHER;
\tself->fb.firing = false; self->fb.jumping = false;
\tVectorClear(self->fb.dir_move_);

\tswitch (fbw_phase[slot]) {
\tcase 0: { /* WALK to the recording's start (frame 0), on the ground */
\t\tfloat tx = tr[0][0], ty = tr[0][1];
\t\tfloat dx = tx - self->s.v.origin[0], dy = ty - self->s.v.origin[1];
\t\tfloat d = sqrt(dx*dx + dy*dy);
\t\tif (d <= FBW_ARRIVE && og) {           /* arrived + grounded -> start replay */
\t\t\tfbw_phase[slot] = 1; fbw_fi[slot] = 0; fbw_timer[slot] = 0;
\t\t\tbreak;
\t\t}
\t\tif (d > 1.0f) {                        /* steer/move toward the start */
\t\t\tself->fb.dir_move_[0] = dx / d;
\t\t\tself->fb.dir_move_[1] = dy / d;
\t\t\tself->fb.dir_move_[2] = 0;
\t\t\tself->fb.desired_angle[PITCH] = 0;
\t\t\tself->fb.desired_angle[YAW] = atan2(dy, dx) * 180.0f / 3.14159265f;
\t\t\tif (og && d > 250.0f) self->fb.jumping = true; /* hop to cover ground */
\t\t}
\t\tif (++fbw_timer[slot] > FBW_WALK_TIMEOUT) {  /* stuck -> snap to grounded start */
\t\t\tvec3_t p; p[0]=tr[0][0]; p[1]=tr[0][1]; p[2]=tr[0][2];
\t\t\tsetorigin(self, PASSVEC3(p)); VectorClear(self->s.v.velocity);
\t\t\tfbw_phase[slot] = 1; fbw_fi[slot] = 0; fbw_timer[slot] = 0;
\t\t}
\t\tbreak;
\t}
\tcase 1: { /* REPLAY the recorded jump frame-by-frame (dense -> smooth) */
\t\tint i = fbw_fi[slot];
\t\tvec3_t p;
\t\tif (i >= n) { fbw_phase[slot] = 2; fbw_timer[slot] = FBW_PAUSE; break; }
\t\tp[0] = tr[i][0]; p[1] = tr[i][1]; p[2] = tr[i][2];
\t\tsetorigin(self, PASSVEC3(p));
\t\tself->s.v.velocity[0] = tr[i][3];   /* recorded velocity -> correct run/jump anim + client interp */
\t\tself->s.v.velocity[1] = tr[i][4];
\t\tself->s.v.velocity[2] = tr[i][5];
\t\tself->fb.desired_angle[PITCH] = tr[i][6];
\t\tself->fb.desired_angle[YAW]   = tr[i][7];
\t\tself->s.v.angles[0] = tr[i][6]; self->s.v.angles[1] = tr[i][7]; self->s.v.angles[2] = 0;
\t\tif (tr[i][8] != 0.0f) sound(self, CHAN_WEAPON, "weapons/rocket1i.wav", 1, ATTN_NORM);
\t\tfbw_fi[slot] = i + 1;
\t\tbreak;
\t}
\tcase 2: /* PAUSE then walk to the next recording */
\t\tif (--fbw_timer[slot] <= 0) {
\t\t\tfbw_idx[slot] = (idx + 1) %% FBW_N;
\t\t\tfbw_phase[slot] = 0; fbw_timer[slot] = 0;
\t\t}
\t\tbreak;
\t}
}
/* ===== /FRAGBOT_BLOCK ===== */

/* ===== FRAGBOT_CALL ===== */
\tif ((int) cvar("k_fb_fragbot_mode") == 33 && !ISDEAD(self))
\t{
\t\tFragBot_RJ(self);
\t}
/* ===== /FRAGBOT_CALL ===== */
''' % {"num": N, "arrays": "\n".join(arrays), "disp_arr": dispatch_arr, "disp_len": dispatch_len}

out = HERE / "fragbot_rj_seam.c"
out.write_text(seam)
print("wrote %s (%d jumps, %d total frames)" % (out, N, sum(lens)))
